### ISSUE TITLE
tasks scheduled incorrectly when using hpx::launch::sync with shared_future<>

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2528]
When attaching multiple .then() continuations to a shared future, incorrect behaviour results when using hpx::launch::sync policy (this is the default).

This snapshot shows the behaviour of a test program when using
```
shared_future1.then(hpx::launch::async, task("CPU gemm") );
shared_future1.then(hpx::launch::async, task("GPU gemm") );
```
(please note that there are many GPU task in the plots that follow and hence lots of small yellow tasks and not just one)
where the shared future is represented by one of the "random a/b/c" tasks that can be seen in the plot. When random finishes, the CPU and GPU gemm tasks begin running and all is as expected.
![screen shot 2017-03-06 at 14 25 53](https://cloud.githubusercontent.com/assets/941548/23611752/d6688776-0278-11e7-8070-306d7fa91b70.png)

The following plot shows what happens if sync policy (or a default empty policy)  is used for one (the first) continuation
```
shared_future1.then( hpx::launch::sync, task("CPU gemm") );
shared_future1.then( hpx::launch::async, task("GPU gemm") );
```
![screen shot 2017-03-06 at 14 22 49](https://cloud.githubusercontent.com/assets/941548/23611702/b1dbc3d2-0278-11e7-86d2-328e2c255102.png)
Here we can see that when "random" completes, the "CPU Gemm" task executes, and the GPU tasks do not run until after the CPU task has completed. One would expect that the shared random future becoming ready would trigger both CPU and GPU tasks to run.

The problem can be explained by observing carefully the task traces where we can see how the CPU future is executed after the "random a" task completes. "Random A" executes the CPU future, and does not make the other GPU futures ready until the CPU task completes. In fact looking at the trace, we can see that the "random a" task is kept alive whilst "async copy" and "CPU gemm" that are continuations on "random a" trigger and then the stack unwinds as each task completes.

The futures that depend on the original future are not set ready until the CPU task completes, instead of being set before it starts - and hence being able to run concurrently. 

![screen shot 2017-03-06 at 14 39 22](https://cloud.githubusercontent.com/assets/941548/23612197/ba94fbd6-027a-11e7-99f3-aef179a4ed71.png)

This behaviour has been found by @rasolca when testing matrix code and he notes that "default sync behaviour is sensible for futures, but not for shared_futures". At least not for ALL of the continuations, because when N continuations are added to a shared future using the default (sync) policy, they end up running sequentially which is disastrous for default behaviour. For shared future continuations, async policy should be the default.

**Comment by hkaiser** [comment]
This is indeed an interesting side effect I have not considered yet. I'm however not sure what the correct behavior should be. In fact, this is one place where HPX (so far) has diverged from what was proposed by the Concurrency TS. The TS mandated for the continuation which was attached by `(shared_)future.then()` to be executed with the same launch policy as the initial future was created with. E.g. if the initial future was generated using `launch::async` then any continuation attached to this future by default should use the same launch policy.

But even if we implemented this as mandated, the described issue would arise. If the first continuation attached to a shared_future uses `launch::sync` and the continuation attached to the same shared_future uses `launch::async` then the second continuation would be launched only after the first continuation has finished executing.

I have the feeling, that no matter what defaults we choose there always will be a use case where the resulting behavior ends up being unexpected. The only suggestion I have in such cases would be to explicitly specify the launch policy for each of the attached continuations.

@rasolca, @biddisco please comment.

**Comment by biddisco** [comment]
We have modified all our continuations for shared futures to use async launch policy and that does solve the problem.

The greater question is indeed, what to do in general for shared futures. A default sync policy implies that all continuations attached will __correctly__ run sequentially, but this would be surprising to the average user. The problem only manifests itself because the default launch policy is __sync__. If the user requests a sync policy and gets sequential behaviour, this could be forgiven as an intended side effect. 

I do not see why having the first continuation as sync, should stop other continuations from running. When the task that generates the shared future ready state becomes ready, it should see/check that there are multiple continuations attached and change their state to pending from suspended (if they are async) and then execute the first one if it is sync. Then other worker threads can steal the tasks if they so choose and the sequential behaviour is avoided.

**Comment by hkaiser** [comment]
@biddisco What is the status of this? Is that still an issue?

**Comment by biddisco** [comment]
I do not know the answer. Yes, it is still an issue because the problem still exists. However, it's not an issue now that we know what the problem is and how to work around it. My suspicion is that this is something that needs to be brought to the attention of the standards committee as it probably has not been addressed anywhere and some kind of correct behaviour should be decided/documented.
